apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cronjob-pg-backup
spec:
  storageClassName: my-managed-premium
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1024Gi

